spring.application.name=pagamentos-ms
server.port=0
# datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=myPassword
# jpa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
# circuit breaker
resilience4j.circuitbreaker.instances.atualizaPedido.slidingWindowSize=6
resilience4j.circuitbreaker.instances.atualizaPedido.minimumNumberOfCalls=4
resilience4j.circuitbreaker.instances.atualizaPedido.failureRateThreshold=50
resilience4j.circuitbreaker.instances.atualizaPedido.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.atualizaPedido.permittedNumberOfCallsInHalfOpenState=2