@baseUrl = http://localhost:55289
@pagamentoId = 1

### Listar pagamentos (paginado)
GET {{baseUrl}}/pagamentos/todos?page=0&size=10&sort=id,desc
Accept: application/json

### Buscar pagamento por id
GET {{baseUrl}}/pagamentos/{{pagamentoId}}
Accept: application/json