@baseUrl = http://localhost:5589
@pagamentoId = 1

### Atualizar pagamento
PUT {{baseUrl}}/pagamentos/{{pagamentoId}}
Content-Type: application/json

{
  "status": "CONFIRMADO",
    "valor": 500,
    "nome": "Sidnei",
    "numero": "12345678",
    "expiracao": "10/29",
    "codigo": "123",
    "pedidoId": 1,
    "formaDePagamentoId": 1
}